version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [ci-cd, dependencies]
    commit-message:
      prefix: ci

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    labels: [backend, dependencies]
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    labels: [frontend, dependencies]
    commit-message:
      prefix: chore
